name: Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - name: Generate Changelog
              id: changelog
              uses: orhun/git-cliff-action@v1
              with:
                  args: --latest --strip header

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  body: ${{ steps.changelog.outputs.changelog }}
